version: '3.8'

services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"  # Mapeia a porta do contêiner para a máquina host
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
